### ISSUE TITLE
Add new axis "PredicateArgumentAxis"

### ISSUE THREAD

**Issue by judithek** [dkpro/dkpro-uby#66]
```
add this axis in the multilingual package:

Attributes:

 id
semanticPredicateOne: IDREF
semanticPredicateTwo: IDREF
semanticArgumentOne: IDREF
semanticArgumentTwo: IDREF
axisType 

lexiconOne, lexiconTwo: String (LexiconId)
    confidence: double
    metaDataId: String 

```

Original issue reported on code.google.com by `eckle.kohler` on 2013-11-18 09:50:20
